### ISSUE TITLE
<!-- htmlmin:ignore-->  is not ignoring attribute

### ISSUE THREAD

**Issue by ajkj** [kangax/html-minifier#366]
#### test code 1

```
var minify = require('html-minifier').minify;
var result = minify(' <!-- htmlmin:ignore --> <p class="logged"|cond="$is_logged === true" id="foo"> bar</p> <!-- htmlmin:ignore -->', {
    removeComments : true
});
console.log(result);
```
### expected

```
<p class="logged"|cond="$is_logged === true" id="foo"> bar</p> 
```
### result

```
<p class="logged" cond="$is_logged === true" id="foo"> bar</p
```

---
#### test code 2

```
var minify = require('html-minifier').minify;

var result = minify('<!-- htmlmin:ignore --> <input {$number >0  ? "checked" : ""} > <!-- htmlmin:ignore -->', {
    removeComments : true
});

console.log(result);
```
#### expected

```
<input {$number >0  ? "checked" : ""} > 
```
#### result

```
parse error
```

**Comment by kangax** [comment]
Should work now

**Comment by calgary007** [comment]
samething. We have this script running on various files. I want the script to ignore a particular html, the whole html file.

I have added  before first line and after last line of HTML file but script still does not ignore that HTML
